apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: getinfo
  namespace: default
  description: "Read details from the Test1 MCP server"
  labels:
    mcp-catalog.io/type: tool
    mcp-catalog.io/server: test1
spec:
  type: mcp-tool
  lifecycle: experimental
  owner: platform-team
  # partOf establishes the tool-to-server relationship (single string, not array)
  partOf: component:default/test1
  mcp:
    toolType: query
    inputSchema:
      type: object
      properties:
        resourceId:
          type: string
          description: "Identifier of the entity to inspect"
      required:
        - resourceId
    outputSchema:
      type: object
      properties:
        metadata:
          type: object
    capabilities:
      - read
      - inspect
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: setinfo
  namespace: default
  description: "Update metadata on the Test1 MCP server"
  labels:
    mcp-catalog.io/type: tool
    mcp-catalog.io/server: test1
spec:
  type: mcp-tool
  lifecycle: experimental
  owner: platform-team
  # partOf establishes the tool-to-server relationship (single string, not array)
  partOf: component:default/test1
  mcp:
    toolType: mutation
    inputSchema:
      type: object
      properties:
        resourceId:
          type: string
          description: "Identifier of the record to update"
        payload:
          type: object
          description: "JSON payload with the new values"
      required:
        - resourceId
        - payload
    outputSchema:
      type: object
      properties:
        status:
          type: string
        updatedAt:
          type: string
          format: date-time
    capabilities:
      - write
      - configure
