# Grant mcp-viewer (read-only) role to dev user
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-viewer-dev
  labels:
    app.kubernetes.io/part-of: mcp-tools-catalog
    app.kubernetes.io/component: rbac-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev
