apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpservers.mcp-catalog.io
  labels:
    app.kubernetes.io/name: mcp-tools-catalog
    app.kubernetes.io/component: crd
spec:
  group: mcp-catalog.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - type
                - version
              properties:
                type:
                  type: string
                  enum:
                    - stdio
                    - sse
                    - websocket
                  description: Connection protocol type
                endpoint:
                  type: string
                  description: Connection endpoint URL or command
                command:
                  type: string
                  description: Command to execute (for stdio type)
                args:
                  type: array
                  items:
                    type: string
                  description: Command arguments
                env:
                  type: object
                  additionalProperties:
                    type: string
                  description: Environment variables
                version:
                  type: string
                  pattern: '^[0-9]+\.[0-9]+\.[0-9]+'
                  description: Server version (semantic versioning)
                capabilities:
                  type: array
                  items:
                    type: string
                    enum:
                      - tools
                      - resources
                      - prompts
                      - sampling
                  description: List of server capabilities
            status:
              type: object
              properties:
                lastUpdated:
                  type: string
                  format: date-time
                  description: ISO timestamp of last update
                toolCount:
                  type: integer
                  minimum: 0
                  description: Number of associated MCPTool entities
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mcpservers
    singular: mcpserver
    kind: MCPServer
    shortNames:
      - mcps
      - mcp-server
  additionalPrinterColumns:
    - name: Type
      type: string
      description: Connection type
      jsonPath: .spec.type
    - name: Version
      type: string
      description: Server version
      jsonPath: .spec.version
    - name: Tools
      type: integer
      description: Number of tools
      jsonPath: .status.toolCount
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
