apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcptools.mcp-catalog.io
  labels:
    app.kubernetes.io/name: mcp-tools-catalog
    app.kubernetes.io/component: crd
spec:
  group: mcp-catalog.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - server
                - type
              properties:
                server:
                  type: string
                  pattern: "^mcpserver:[a-z0-9-]+/[a-z0-9-]+$"
                  description: "EntityRef to parent MCPServer (format: mcpserver:namespace/name)"
                type:
                  type: string
                  description: Tool type/category
                inputSchema:
                  type: object
                  description: JSON Schema for tool parameters
                  x-kubernetes-preserve-unknown-fields: true
                capabilities:
                  type: array
                  items:
                    type: string
                  description: Specific tool capabilities
                parameters:
                  type: array
                  items:
                    type: string
                  description: Parameter definitions
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mcptools
    singular: mcptool
    kind: MCPTool
    shortNames:
      - mcpt
      - mcp-tool
  additionalPrinterColumns:
    - name: Server
      type: string
      description: Parent server
      jsonPath: .spec.server
    - name: Type
      type: string
      description: Tool type
      jsonPath: .spec.type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
