apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpworkloads.mcp-catalog.io
  labels:
    app.kubernetes.io/name: mcp-tools-catalog
    app.kubernetes.io/component: crd
spec:
  group: mcp-catalog.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - type
                - purpose
              properties:
                type:
                  type: string
                  description: Workload type
                purpose:
                  type: string
                  description: Purpose/description of the workload
                tools:
                  type: array
                  items:
                    type: string
                    pattern: "^mcptool:[a-z0-9-]+/[a-z0-9-]+$"
                  description: "Array of MCPTool entity references (format: mcptool:namespace/name)"
                deploymentInfo:
                  type: object
                  properties:
                    schedule:
                      type: string
                      description: Schedule for scheduled workloads (cron format)
                    runtime:
                      type: string
                      description: Runtime environment
                    environment:
                      type: string
                      description: Deployment environment
                dependencies:
                  type: array
                  items:
                    type: string
                  description: Other workload dependencies
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mcpworkloads
    singular: mcpworkload
    kind: MCPWorkload
    shortNames:
      - mcpw
      - mcp-workload
  additionalPrinterColumns:
    - name: Type
      type: string
      description: Workload type
      jsonPath: .spec.type
    - name: Purpose
      type: string
      description: Workload purpose
      jsonPath: .spec.purpose
    - name: Tools
      type: integer
      description: Number of tools
      jsonPath: .spec.tools.length()
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
